"use strict";

(() => {
  const el = (name) => document.getElementById(`summary-${name}`);
  let revision = 0;
  let pending = null;
  let recordingSummaryKey = null;

  window.onevoiceRecordingSummary = (item) => {
    if (!item) return;
    const key = `${item.path}|${item.status}`;
    if (key === recordingSummaryKey) return;
    recordingSummaryKey = key;
    el("view").textContent = item.status === "loading"
      ? "Summary preparing…"
      : item.status === "ready" ? "View summary" : "Summary needs attention";
    clearResult();
    if (item.status === "ready") {
      show(item.result);
      el("status").textContent = "Summary saved with your recording.";
    } else {
      el("status").textContent = item.error || "Gemini is summarizing your recording…";
    }
  };

  function controls() {
    el("run").disabled = Boolean(pending);
  }

  function clearResult() {
    revision += 1;
    if (pending) pending.abort();
    pending = null;
    el("text").textContent = "";
    el("points").replaceChildren();
    controls();
  }

  function show(result) {
    el("text").textContent = result.summary;
    el("points").replaceChildren();
    result.key_points.forEach((point) => {
      const item = document.createElement("li");
      item.textContent = point;
      el("points").append(item);
    });
    el("status").textContent = "Generated by Gemini. Check it against what was said.";
    controls();
  }

  async function run() {
    if (pending) return;
    clearResult();
    const epoch = revision;
    const controller = new AbortController();
    pending = controller;
    const timeout = setTimeout(() => controller.abort(), 30000);
    el("status").textContent = "Sending the transcript to Gemini…";
    controls();
    try {
      const response = await fetch("/api/summarize", {
        method: "POST",
        headers: {"Content-Type": "application/json", "X-OneVoice-UI": "1"},
        body: "{}",
        signal: controller.signal,
      });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Request failed.");
      if (revision !== epoch) return;
      show(result);
    } catch (error) {
      if (revision === epoch) {
        el("status").textContent =
          error.name === "AbortError"
            ? "Request timed out. Please retry."
            : error.message;
      }
    } finally {
      clearTimeout(timeout);
      if (revision === epoch) {
        pending = null;
        controls();
      }
    }
  }

  el("view").addEventListener("click", () => {
    const opening = el("panel").hidden;
    el("panel").hidden = !opening;
    el("view").setAttribute("aria-expanded", String(opening));
    if (opening) {
      el("panel").scrollIntoView?.({behavior: "smooth", block: "nearest"});
      el("heading").focus?.({preventScroll: true});
    }
  });
  el("run").addEventListener("click", run);
  window.addEventListener("pagehide", clearResult);
})();
