const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');

const htmlPath = path.resolve(__dirname, '../../demo/web_ui/index.html');
const scriptPath = path.resolve(__dirname, '../../demo/web_ui/summary.js');

function harness(fetch = async () => { throw Error('Unexpected network'); }) {
  const elements = new Map();
  function element() {
    return {value: '', textContent: '', hidden: false, children: [], listeners: {},
      addEventListener(name, fn) { this.listeners[name] = fn; },
      replaceChildren() { this.children = []; }, append(child) { this.children.push(child); },
      setAttribute(name, value) { this[name] = value; },
      fire(name = 'click') { return this.listeners[name](); }};
  }
  const html = fs.readFileSync(htmlPath, 'utf8');
  for (const [, id] of html.matchAll(/id="(summary-[^"]+)"/g)) elements.set(id, element());
  const calls = [];
  const document = {getElementById: id => {assert.ok(elements.has(id), id); return elements.get(id);}, createElement: element};
  const context = {
    document, window: {addEventListener() {}},
    fetch: async (url, options) => { calls.push({url, body: options.body}); return fetch(url, options); },
    AbortController, setTimeout, clearTimeout,
  };
  vm.runInNewContext(fs.readFileSync(scriptPath, 'utf8'), context);
  return {el: name => elements.get('summary-' + name), calls, window: context.window};
}

const GOOD = async () => ({ok: true, json: async () => ({summary: 'They agreed on lunch.', key_points: ['Noon', 'Cafe']})});
const points = (h) => h.el('points').children.map((li) => li.textContent);

test('Summarize posts an empty body so the server uses its own transcript', async () => {
  const h = harness(GOOD);
  await h.el('run').fire();
  assert.equal(h.calls.length, 1);
  assert.equal(h.calls[0].url, '/api/summarize');
  assert.equal(h.calls[0].body, '{}');
  assert.equal(h.el('text').textContent, 'They agreed on lunch.');
  assert.deepEqual(JSON.parse(JSON.stringify(points(h))), ['Noon', 'Cafe']);
  assert.match(h.el('status').textContent, /Generated by Gemini/);
  assert.equal(h.el('run').disabled, false);
});

test('the status says the transcript is being sent while the request is in flight', async () => {
  let release;
  const gate = new Promise((resolve) => { release = resolve; });
  const h = harness(async () => { await gate; return GOOD(); });
  const running = h.el('run').fire();
  assert.match(h.el('status').textContent, /Sending the transcript to Gemini/);
  assert.equal(h.el('run').disabled, true);
  release();
  await running;
  assert.equal(h.el('run').disabled, false);
});

test('a server error is shown and nothing else changes', async () => {
  const h = harness(async () => ({ok: false, json: async () => ({error: 'No captions yet.'})}));
  await h.el('run').fire();
  assert.match(h.el('status').textContent, /No captions yet/);
  assert.equal(h.el('text').textContent, '');
  assert.equal(h.el('run').disabled, false);
});

test('a summary for a recording appears in the panel and updates the dock label', () => {
  const h = harness();
  h.window.onevoiceRecordingSummary({path: 'a', status: 'loading'});
  assert.equal(h.el('view').textContent, 'Summary preparing…');
  assert.match(h.el('status').textContent, /Gemini is summarizing/);
  h.window.onevoiceRecordingSummary({path: 'a', status: 'ready', result: {summary: 'Recap.', key_points: ['One']}});
  assert.equal(h.el('view').textContent, 'View summary');
  assert.equal(h.el('text').textContent, 'Recap.');
  assert.match(h.el('status').textContent, /saved with your recording/);
});

test('the View summary button shows and hides the panel', () => {
  const h = harness();
  h.el('panel').hidden = true;
  h.el('view').fire();
  assert.equal(h.el('panel').hidden, false);
  assert.equal(h.el('view')['aria-expanded'], 'true');
  h.el('view').fire();
  assert.equal(h.el('panel').hidden, true);
});

test('the panel has no speak, sample, auto-speak or clear controls, and never calls the speech endpoint', async () => {
  const html = fs.readFileSync(htmlPath, 'utf8');
  for (const id of ['summary-speak', 'summary-auto', 'summary-sample', 'summary-clear', 'summary-badge']) {
    assert.doesNotMatch(html, new RegExp(`id="${id}"`), id);
  }
  const source = fs.readFileSync(scriptPath, 'utf8');
  assert.doesNotMatch(source, /api\/speak|Audio\(|speak|sample|scripted/i);
  const h = harness(GOOD);
  await h.el('run').fire();
  assert.ok(h.calls.every((call) => call.url === '/api/summarize'));
});
